"""add visualization_spec to messages.

Revision ID: ce838d7a3ddf
Revises: 705868b2de7b
Create Date: 2025-10-27 15:27:46.918045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce838d7a3ddf"
down_revision: Union[str, Sequence[str], None] = "705868b2de7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("visualization_spec", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "visualization_spec")
    # ### end Alembic commands ###
