from core.exceptions.base import (
    AuthenticationError,
    AuthorizationError,
    BadRequestException,
    CacheError,
    ConfigurationError,
    DatabaseError,
    ExternalServiceError,
    IgniteLensBaseError,
    InternalServerException,
    NotFoundError,
    NotFoundException,
    ValidationError,
)
from core.exceptions.connector import (
    ConnectionPoolExhaustedError,
    ConnectionTestFailedError,
    ConnectionTimeoutError,
    ConnectorError,
    InvalidCredentialsError,
    QueryExecutionError,
    QueryTimeoutError,
    UnsupportedConnectorError,
)
from core.exceptions.handlers import (
    database_exception_handler,
    database_operational_exception_handler,
    generic_exception_handler,
    http_exception_handler,
    ignite_lens_exception_handler,
    starlette_http_exception_handler,
    validation_exception_handler,
)
from core.exceptions.session import (
    DatasourceNotFoundError,
    InvalidSessionStateError,
    LLMConfigNotFoundError,
    SessionAccessDeniedError,
    SessionExpiredError,
    SessionNotFoundError,
)

__all__ = [
    # Base exceptions
    "IgniteLensBaseError",
    "AuthenticationError",
    "AuthorizationError",
    "BadRequestException",
    "CacheError",
    "ConfigurationError",
    "DatabaseError",
    "ExternalServiceError",
    "InternalServerException",
    "NotFoundError",
    "NotFoundException",
    "ValidationError",
    # Connector exceptions
    "ConnectorError",
    "ConnectionTestFailedError",
    "QueryExecutionError",
    "UnsupportedConnectorError",
    "ConnectionPoolExhaustedError",
    "ConnectionTimeoutError",
    "QueryTimeoutError",
    "InvalidCredentialsError",
    # Session exceptions
    "SessionNotFoundError",
    "SessionExpiredError",
    "InvalidSessionStateError",
    "SessionAccessDeniedError",
    "DatasourceNotFoundError",
    "LLMConfigNotFoundError",
    # Exception handlers
    "ignite_lens_exception_handler",
    "database_exception_handler",
    "database_operational_exception_handler",
    "generic_exception_handler",
    "http_exception_handler",
    "starlette_http_exception_handler",
    "validation_exception_handler",
]
